baseURL = 'https://docs.ventuscloud.eu/'
languageCode = "en-us"
title = "EWW | ITandTEL Cloud Docs"
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "mine"
# Change the title separator. Default to "::".
titleSeparator = "-"
